# Generated by Django 4.1.5 on 2023-01-11 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=80, null=True)),
                ('lastname', models.CharField(default=None, max_length=80, null=True)),
                ('dob', models.DateField(default=datetime.datetime(2023, 1, 11, 22, 6, 47, 425371))),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.BigIntegerField(default=0)),
                ('type', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], default=None, max_length=10)),
                ('password', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
