# Generated by Django 4.1.5 on 2023-01-11 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bombay', '0002_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2023, 1, 11, 22, 45, 18, 9317)),
        ),
    ]
