# Generated by Django 4.1.5 on 2023-01-11 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bombay', '0003_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 1, 7, 35, 373020)),
        ),
    ]
