# Generated by Django 4.1.5 on 2023-01-15 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bombay', '0006_alter_user_dob_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 16, 10, 25, 1570)),
        ),
    ]
